name: Validate Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET for this Heavy Metal Machine
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the Heavy Metal Machine
        run: dotnet build --no-restore
      - name: Sound check
        run: dotnet test --no-build --verbosity normal
        env:
          ASPNETCORE_ENVIRONMENT: Testing
